# Generated by Django 2.2.13 on 2021-04-15 14:17

from django.db import migrations

def crearRoles(apps, schema_editor):
    try:
        Rol = apps.get_model("api", 'Rol')

        Rol.objects.create(nombre_rol="administrador")
        Rol.objects.create(nombre_rol="profesor")
        Rol.objects.create(nombre_rol="estudiante")
    except Exception as e:
        print("Error al crear roles: ", (str(e)))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210415_1350'),
    ]

    operations = [
        migrations.RunPython(crearRoles)
    ]
