from .profile import Profile
from .Asignacion import Asignacion
from .AsignacionEstudiante import Asignarestudiante
from .CicloEscolar import Ciclo
from .Curso import Curso
from .Estudiante import Estudiante
from .Eventos import Evento
from .Grado import Grado
from .Material import Material
from .Nivel import Nivel
from .Profesion import Profesion
from .Profesor import Profesor
from .rol import Rol
from .Seccion import Seccion
from .Tarea import Tarea
from .TareaEstudiante import TareaEs
