from .user import UserSerializer, UserReadSerializer
from .registroSerializer import CatedraticoRegistroSerializer, CatedraticoSerializer
from .profesionSerializer import ProfesionRegistroSerializer, ProfesionSerializer
from .estudianteSerializer import EstudianteRegistroSerializer, EstudianteSerializer
from .estudianteUpdateSerializer import EstudianteUpdateSerializer
from .nivelSerializer import NivelRegistroSerializer, NivelSerializer
from .gradoSerializer import GradoRegistroSerializer, GradoSerializer
from .cursoSerializer import CursoRegistroSerializer, CursoSerializer
from .profesorUpdateSerializer import ProfesorUpdateSerializer
from .seccionSerializer import SeccionRegistroSerializer, SeccionSerializer
from .cicloSerializer import CicloRegistroSerializer, CicloSerializer
from .eventoSerializer import EventoRegistroSerializer, EventoSerializer
